/**
 * Typed response payload from GET /api/v1/status.
 * This is the handshake payload the device returns on connection.
 */
export interface DeviceStatus {
  /** Unique identifier for this device, e.g. "VAHA-88291-A" */
  readonly device_id: string;
  /** Semantic version of the device firmware, e.g. "1.0.4" */
  readonly firmware_version: string;
  /** API version string exposed by the device, e.g. "v1" */
  readonly api_version: string;
  /** Feature flags the device supports */
  readonly capabilities: readonly DeviceCapability[];
  /** Battery percentage 0–100, or null if not applicable */
  readonly battery_percentage: number | null;
  /** Number of audio captures currently buffered on the device */
  readonly buffered_captures_count: number;
  /** Total bytes used in device flash storage */
  /** Total bytes used in device flash storage */
  readonly storage_used_bytes: number;
  /** Uptime in seconds */
  readonly uptime_seconds?: number;
  /** CPU usage percentage */
  readonly cpu_percent?: number;
  /** Memory used in bytes */
  readonly memory_used_bytes?: number;
  /** IP address */
  readonly ip_address?: string;
  /** MAC address */
  readonly mac_address?: string;
  /** Microphone status */
  readonly microphone_active?: boolean;
}

/**
 * Capability flags advertised by the device on the /status endpoint.
 * The app uses these to enable or disable features at runtime.
 */
export type DeviceCapability = "sensors" | "audio_flac" | "audio_pcm" | "ota";

/**
 * Minimal metadata for a capture stored on the device.
 * Returned by GET /api/v1/captures (list endpoint — no audio payload).
 */
export interface DeviceCaptureMetadata {
  /** Device-generated transaction identifier */
  readonly transaction_id: string;
  /** ISO 8601 timestamp of when the capture was recorded */
  readonly captured_timestamp: string;
  /** Audio encoding format */
  readonly audio_encoding: "FLAC" | "PCM" | "WAV";
  /** Audio sample rate in Hz */
  readonly sample_rate: number;
  /** Number of audio channels */
  readonly channels: number;
  /** Size of the audio payload in bytes */
  readonly audio_size_bytes: number;
  /** MD5 checksum of the audio payload for integrity verification */
  readonly audio_md5: string;
  /** The speech-to-text transcript generated by Whisper */
  readonly transcript: string;
  /** Telemetry data captured alongside the audio */
  readonly telemetry_metrics: DeviceTelemetry;
}

/**
 * Sensor telemetry data captured at the time of voice recording.
 */
export interface DeviceTelemetry {
  readonly temperature_celsius: number | null;
  readonly humidity_percentage: number | null;
  readonly voc_parts_per_billion: number | null;
  readonly liquid_flow: {
    readonly rate_liters_per_minute: number | null;
    readonly accumulated_volume_liters: number | null;
  } | null;
}

/**
 * Live sensor reading returned by GET /api/v1/sensors/current.
 */
export interface LiveSensorReading {
  readonly temperature_celsius: number | null;
  readonly humidity_percentage: number | null;
  readonly voc_parts_per_billion: number | null;
  readonly flow_rate_liters_per_minute: number | null;
  readonly accumulated_volume_liters: number | null;
  readonly sampled_at: string;
}
